In [1]:
import tensorflow as tf

# reshape

In [3]:
a = tf.constant([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [7.0, 8.0, 9.0, 10.0, 11.0, 12.0]])
print(a)

b = tf.reshape(a, (2, 2, 3))
print(b)

tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)
